apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:volsync-operatorpolicy-aggregate-clusterrole
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
  - apiGroups: ["policy.open-cluster-management.io"]
    resources: ["operatorpolicies"]
    verbs: ["get", "create", "delete", "update"]
