---
version: "2"
linters:
  # Defaults are still enabled, see:
  #  https://golangci-lint.run/usage/linters/#enabled-by-default
  #
  # Enable these specific additional linters to match what
  # sonar checks for
  enable:
    - funlen
    - lll
    - misspell
    - unparam
  settings:
    funlen:
      statements: -1
      ignore-comments: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
          - staticcheck
        text: 'should not use dot imports'
        source: . "github.com/onsi/(ginkgo/v2|gomega)"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
