version: "2"
linters:
  enable:
    - funlen
    - lll
    - misspell
    - unparam
  settings:
    funlen:
      statements: -1
      ignore-comments: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
