apiVersion: v1
entries:
  volsync:
  - annotations:
      artifacthub.io/changes: |
        - kind: changed
          description: Restic updated to v0.17.0
        - kind: changed
          description: Syncthing updated to v1.27.12
        - kind: added
          description: moverAffinity added to spec to allow for specifying the podAffinity assigned to a VolSync mover pod
        - kind: added
          description: cleanupTempPVC option added for direct users to allow for deleting the dynamically provisioned destination PVC after a completed replication.
        - kind: added
          description: cleanupCachePVC option for restic to allow for deleting the cache PVC after a completed replication.
        - kind: added
          description: enableFileDeletion restic option to allow for restoring to an existing PVC (for example running multiple restores) and delete files that do not exist in the backup being restored.
      artifacthub.io/crds: |
        - kind: ReplicationDestination
          version: v1alpha1
          name: replicationdestination.volsync.backube
          displayName: Replication destination
          description: Defines the destination of a replicated volume
        - kind: ReplicationSource
          version: v1alpha1
          name: replicationsource.volsync.backube
          displayName: Replication source
          description: Defines the source of a replicated volume
      artifacthub.io/license: AGPL-3.0-or-later
      artifacthub.io/operator: "true"
      artifacthub.io/operatorCapabilities: Basic Install
      artifacthub.io/signKey: |
        fingerprint: 2C937ADACD4BEF921197F66EDC7556B1903A252B
        url: https://keys.openpgp.org/vks/v1/by-fingerprint/2C937ADACD4BEF921197F66EDC7556B1903A252B
    apiVersion: v2
    appVersion: 0.11.0-rc.1
    created: "2024-11-04T15:59:46.704106-05:00"
    description: Asynchronous data replication for Kubernetes
    digest: 10f7efb5e4c08f727813ff488231a926043303b3fd17a0e3775be2e7f4f3e3ec
    home: https://volsync.readthedocs.io/
    icon: https://raw.githubusercontent.com/backube/volsync/main/docs/media/volsync.svg?sanitize=true
    keywords:
    - backup
    - csi
    - data
    - disaster recovery
    - replication
    - storage
    kubeVersion: ^1.20.0-0
    maintainers:
    - email: jstrunk@redhat.com
      name: John Strunk
      url: https://github.com/JohnStrunk
    - email: tflower@redhat.com
      name: Tesshu Flower
      url: https://github.com/tesshuflower
    name: volsync
    sources:
    - https://github.com/backube/volsync
    type: application
    urls:
    - volsync-0.11.0-rc.1.tgz
    version: 0.11.0-rc.1
generated: "2024-11-04T15:59:46.696596-05:00"
